version: "3"

services:
  api:
    container_name: oc-api
    # image: oc-adonis-api
    # restart:  always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    ports:
      - 3333:3333
  db:
    container_name: oc-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}  
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
  nginx:
    image:  nginx
    ports:
      - "8586:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf.ro
# volumes:
#   postgres-data  